e_shop/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import ProductViewSet, OrderViewSet, Cart, get_token_view

router = routers.DefaultRouter()
router.register('products', ProductViewSet)
router.register('order', OrderViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('cart/', Cart.as_view(), name='cart-list'),
    path('csrf/', get_token_view, name='csrf')
]

e_shop/e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

HOME_PAGE_URL = 'products/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', RedirectView.as_view(url=HOME_PAGE_URL))
]

e_shop/shop/urls.py
from django.urls import path

from shop.views import (
        ProductListView,
        ProductDetailView,
        ProductCreateView,
        ProductUpdateView,
        ProductDeleteView,
        AddToCart,
        CartListView,
        DeleteFromCart,
        OrderView,
        UserOrder,
    )


app_name = 'shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('<int:pk>', ProductDetailView.as_view(), name='product-detail'),
    path('add', ProductCreateView.as_view(), name='product-add'),
    path('<int:pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('<int:pk>/delete', ProductDeleteView.as_view(), name='product-delete'),
    path('<int:pk>/add/cart', AddToCart.as_view(), name='add-to-cart'),
    path('cart/products', CartListView.as_view(), name='cart-products-list'),
    path('cart/product/<int:pk><str:all_>/delete', DeleteFromCart.as_view(), name='cart-product-delete'),
    path('cart/order', OrderView.as_view(), name='order'),
    path('user/order', UserOrder.as_view(), name='user-order'),
]

e_shop/shop/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator


class Product(models.Model):
    product = models.CharField(max_length=100, blank=False, null=False, verbose_name='Наименование товара')
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name='Описание')
    balance = models.PositiveIntegerField(verbose_name='Остаток', validators=[MinValueValidator(0)])
    category = models.ForeignKey(
        'shop.Category',
        on_delete=models.PROTECT,
        related_name='products',
        default=1,
        verbose_name='Категория'
    )
    price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name='Цена',
        validators=[MinValueValidator(0)]
    )

    class Meta:
        db_table = 'products'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.product}'


class Category(models.Model):
    category = models.CharField(max_length=100, blank=False, null=False, verbose_name='Категория')

    class Meta:
        db_table = 'categories'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.category}'


class Order(models.Model):
    product = models.ManyToManyField(
        'shop.Product',
        related_name='order',
        verbose_name='Товары',
        through='shop.OrderProduct',
        through_fields=('order', 'products')
    )
    user_name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Имя')
    user_phone = models.CharField(max_length=20, blank=False, null=False, verbose_name='Телефон')
    user_address = models.CharField(max_length=200, blank=False, null=False, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True)
    _user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders', default=None, null=True, verbose_name='Пользователь')

    class Meta:
        db_table = 'orders'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.user_name}  {self.user_phone}  {self.user_address}'


class OrderProduct(models.Model):
    products = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='p_order', verbose_name='Товары')
    order = models.ForeignKey('shop.Order', on_delete=models.CASCADE, related_name='products', verbose_name='Заказ')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    class Meta:
        db_table = 'order_products'
        verbose_name = 'Товар/заказ'
        verbose_name_plural = 'Товары/заказ'

    def __str__(self):
        return f'{self.order}{self.products}{self.quantity}'

e_shop/shop/forms.py
from django.forms import ModelForm, TextInput, Textarea, Select, NumberInput
from django import forms

from shop.models import Product, Order


class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = ['category', 'product', 'description', 'price', 'balance']

        widgets = {
            'category': Select(attrs={
                'class': 'form-control'
            }),
            'product': TextInput(attrs={
                'class': 'form-control'
            }),
            'description': Textarea(attrs={
                'class': 'form-control'
            }),
            'price': NumberInput(attrs={
                'class': 'form-control'
            }),
            'balance': NumberInput(attrs={
                'class': 'form-control'
            }),
        }


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30)


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user_name', 'user_address', 'user_phone']

        widgets = {
            'user_name': TextInput(attrs={
                'class': 'form-control'
            }),
            'user_address': TextInput(attrs={
                'class': 'form-control'
            }),
            'user_phone': TextInput(attrs={
                'class': 'form-control'
            })
        }


# class ProductCartForm(ModelForm):
#     class Meta:
#         model = ProductCart
#         fields = ['quantity']

e_shop/shop/views/cart.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, View
from django.shortcuts import redirect, get_object_or_404

from shop.models import Product, Order, OrderProduct
from shop.forms import OrderForm


class AddToCart(View):
    def get(self, request, pk):
        qty = int(request.GET.get('qty'))
        if qty > 0:
            product = get_object_or_404(Product, id=pk)

            if not request.session.get('cart'):
                request.session['cart'] = dict()
            _cart = request.session.get('cart')

            if not _cart.get(str(product.id)):
                _cart[str(product.id)] = 0
            balance = product.balance - (_cart.get(str(product.id)) + qty)
            if balance >= 0:
                _cart[str(product.id)] += qty
                messages.add_message(request, messages.SUCCESS, f' "{product.product}"  добавлен в корзину. Количество: {qty}шт')
            else:
                messages.add_message(request, messages.ERROR, f'Выбранное количество превышает осаток на складе "{product.product}"')

            request.session['cart'] = _cart

        redirect_url = 'shop:product-list'
        if request.GET.get('prev'):
            redirect_url = request.GET.get('prev')
        return redirect(redirect_url)


class DeleteFromCart(View):

    def get(self, request, pk, all_):
        product = get_object_or_404(Product, id=pk)
        _cart = request.session.get('cart')

        if all_ == 'True':
            messages.add_message(request, messages.WARNING, f'"{product.product}" удален из корзины.')
            del _cart[str(product.id)]

        if _cart.get(str(product.id)):
            if _cart[str(product.id)] > 1:
                _cart[str(product.id)] -= 1
                messages.add_message(request, messages.WARNING, f'"{product.product}" удален из корзины. Количество: 1шт')
            else:
                messages.add_message(request, messages.WARNING, f'"{product.product}" удален из корзины.')
                del _cart[str(product.id)]

        request.session['cart'] = _cart

        if not _cart:
            return redirect('shop:product-list')

        return redirect('shop:cart-products-list')


class CartListView(ListView):
    template_name = 'cart/list.html'
    context_object_name = 'products'
    form_class = OrderForm
    cart = {}
    products = []

    def get_queryset(self):
        queryset = {}
        self.cart = self.request.session.get('cart', {})
        for idx, count in self.cart.items():
            product = get_object_or_404(Product, id=int(idx))
            queryset[product] = [count, count*product.price]
        return queryset

    def get_sum(self):
        sum = 0
        self.products = [get_object_or_404(Product, id=int(idx)) for idx in self.cart.keys()]
        for product in self.products:
            sum += self.cart[str(product.id)] * product.price
        return sum

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sum'] = self.get_sum()
        context['form'] = self.form_class
        context['qty'] = False
        return context


class OrderView(View):
    def post(self, request):
        order = None
        order_form = OrderForm(data=self.request.POST)
        _cart = request.session.get('cart')

        if order_form.is_valid():
            order = Order.objects.create(
                user_name=order_form.cleaned_data.get('user_name'),
                user_phone=order_form.cleaned_data.get('user_phone'),
                user_address=order_form.cleaned_data.get('user_address')
                )
            if request.user in get_user_model().objects.all():
                order._user = request.user
            order.save()

        for idx, qty in _cart.items():
            product = get_object_or_404(Product, id=int(idx))
            OrderProduct.objects.create(products=product, quantity=qty, order=order)
            if product.balance - qty >= 0:
                product.balance -= qty
            else:
                order.delete()
                messages.add_message(request, messages.ERROR, f'Произошла ошибка! Количество "{product.product}" на складе {product.balance} шт.')
                return redirect('shop:cart-products-list')
            product.save()
        _cart.clear()
        request.session['cart'] = _cart

        return redirect('shop:product-list')


class UserOrder(LoginRequiredMixin, ListView):
    template_name = 'cart/user_order.html'
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = {}
        orders = Order.objects.filter(_user=self.request.user.id)
        for order in orders:
            inter = {}
            total_order_sum = 0
            for prod in order.products.all():
                inter[prod] = prod.products.price * prod.quantity
            total_order_sum += sum(inter.values())
            queryset[order] = [inter, total_order_sum]
        return queryset

e_shop/shop/views/products.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import reverse

from shop.models import Product, Category
from shop.forms import ProductForm, SearchForm


class ProductListView(ListView):
    template_name = 'products/list.html'
    context_object_name = 'products'
    model = Product
    search_form = SearchForm()
    ordering = '-category', 'product'
    paginate_by = 10
    category = None
    search_item = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.search_form
        context['categories'] = Category.objects.all()
        if self.search_item:
            context['query'] = urlencode({'search': self.search_item})
        if self.request.session.get('cart'):
            qty = 0
            for key, value in self.request.session.get('cart').items():
                qty += value
            context['qty'] = qty
        return context

    def get(self, request, **kwargs):
        self.category = request.GET.get('product/category')
        self.search_item = request.GET.get('search')
        return super().get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().filter(balance__gt=0)
        if self.search_item:
            queryset = queryset.filter(product__contains=self.search_item)
        if self.category:
            queryset = queryset.filter(category=self.category)
        return queryset


class ProductDetailView(DetailView):
    template_name = 'products/detail.html'
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'products/add.html'
    model = Product
    form_class = ProductForm
    permission_required = 'shop.add_product'

    def get_success_url(self):
        return reverse('shop:product-detail', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'products/update.html'
    model = Product
    form_class = ProductForm
    permission_required = 'shop.change_product'

    def get_success_url(self):
        return reverse('shop:product-detail', kwargs={'pk': self.kwargs.get('pk')})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'products/delete.html'
    model = Product
    success_url = reverse_lazy('shop:product-list')
    permission_required = 'shop.delete_product'

e_shop/shop/templates/products/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'partial/nav_bar.html' %}
    <div class="card-body">
        <form action="{% url 'shop:product-add' %}" method="POST">
            {% include 'partial/form.html' %}
        <div class="card-footer d-flex flex-row justify-content-end">
            <div>
                <div class="text-center"><input class="btn btn-success mr-3" type="submit" value="Добавить"/></div>
            </div>
            <div>
                <a class="btn btn-secondary" href="{% url 'shop:product-list' %}">Отменить</a>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

e_shop/shop/templates/products/delete.html
 <div class="modal" id=modal tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Удаление товара</h5>
            <button type="button"  data-bs-dismiss="modal" aria-label="Close">X</button>
          </div>
          <div class="modal-body cb">
            <p><i>Вы уверены,что хотите удалить:</i></p>
              <p>{{ product.product }}</p>
          </div>
          <div class="modal-footer">
          <form action="{% url 'shop:product-delete' product.id %}" method="post">
              {% csrf_token %}
              <div class="d-flex flex-row justify-content-end">
                  <div><a class="btn btn-success mr-3" href="{% url 'shop:product-detail' product.id %}">Нет, отменить</a></div>
                  <div><input type="submit" class="btn btn-danger" value="Да, удалить!"></div>
              </div>
          </form>
          </div>
        </div>
      </div>
    </div>

e_shop/shop/templates/products/detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'partial/nav_bar.html' %}
    <div class="card">
      <div class="card-body">
        <table class="table">
            <tr>
                <td>Категория:</td>
                <td>{{ product.category }}</td>
            </tr>
            <tr>
                <td>Наименование:</td>
                <td>{{ product.product | wordwrap:8 }}</td>
            </tr>
            <tr>
                <td>Описание: </td>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <td>Цена:</td>
                <td>{{ product.price }}</td>
            </tr>
            <tr>
                <td>В наличии:</td>
                <td>{{ product.balance }}</td>
            </tr>
        </table>
          <div class="text-right">
              <form action="{% url 'shop:add-to-cart' product.id %}" method="GET">
                  <input type="number" name="qty" value="1">
                  <button class="btn btn-warning btn-sm text-dark" name="prev" value="{{ request.get_full_path }}" type="submit"><i class="fas fa-cart-plus">  в корзину</i></button>
              </form>
{#                <a class="btn btn-warning btn-sm text-dark" href="{% url 'shop:add-to-cart' product.id %}?prev={{ request.path }}"><i class="fas fa-cart-plus">  в корзину</i></a>#}
          </div>
      </div>
        <div class="card-footer d-flex flex-row justify-content-end">
            <div>
                {% if perms.shop.change_product %}
                <a class="btn btn-secondary mr-3" href="{% url 'shop:product-update' product.id %}">Изменить</a>
                {% endif %}
            </div>
            <div>
                {% if perms.shop.delete_product %}
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal">Удалить</button>
                {% endif %}
            </div>
        </div>
    </div>
    {% include 'products/delete.html' %}
{% endblock %}

e_shop/shop/templates/products/list.html
{% extends 'base.html' %}

{% block content %}
    {% include 'partial/nav_bar.html' %}
    <table class="table table-striped border-0">
      <thead>
        <tr class="border-0">
          <th scope="col">
              <ul class="nav-bar nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle c-link t-link" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Категория
                  </a>
                  <ul class="px-2 dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="c-link" href="{% url 'shop:product-list' %}"><li class="py-1">Все</li></a>
                      {% for category in categories %}
                    <a class="c-link t-link" href="{% url 'shop:product-list'  %}?product/category={{ category.id }}"><li class="py-1">{{ category.category }}</li></a>
                      {% endfor %}
                  </ul>
                </li>
              </ul>
          </th>
          <th class="align-middle t-link" scope="col">Наименование</th>
          <th class="align-middle t-link" scope="col">Цена</th>
            <th class="align-middle t-link" scope="col">
                {% if qty %}
                    <a class="btn btn-warning btn-sm" href="{% url 'shop:cart-products-list' %}">
                        <i class="fas fa-shopping-cart"> в корзине: <span class="badge rounded-pill bg-light text-dark">{{ qty }}</span></i>
                    </a>
                {%  endif %}
            </th>
        </tr>
      </thead>
      <tbody class="border-0">
          {% for product in products %}
            <tr>
              <td class="pl-4"><a class="product-link" href="{% url 'shop:product-list' %}?product/category={{ product.category.id }}">{{ product.category }}</a></td>
              <td><a class="product-link" href="{% url 'shop:product-detail' product.id %}">{{ product.product | truncatechars_html:40  }}</a></td>
              <td>{{ product.price }}</td>
                <td>
              <form action="{% url 'shop:add-to-cart' product.id %}" method="GET">
                  <input type="number" name="qty" value="1" style="width: 50px">
                  <button class="btn btn-warning btn-sm text-dark" name="prev" value="{{ request.get_full_path }}" type="submit"><i class="fas fa-cart-plus">  в корзину</i></button>
              </form>
                </td>
{#                <td><a class="btn btn-warning btn-sm text-dark" href="{% url 'shop:add-to-cart' product.id %}?prev={{ request.get_full_path }}"><i class="fas fa-cart-plus">  в корзину</i></a></td>#}
            </tr>
          {% empty %}
          <tr><td>Нет товаров</td></tr>
          {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %}
        {% include 'partial/paginate.html' %}
    {% endif %}
{% endblock %}

e_shop/shop/templates/products/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'partial/nav_bar.html' %}
    <div class="card-body">
        <form action="" method="POST">
            {% include 'partial/form.html' %}
        <div class="card-footer d-flex flex-row justify-content-end">
            <div>
                <div class="text-center"><input class="btn btn-success mr-3" type="submit" value="Сохранить изменения"/></div>
            </div>
            <div>
                <a class="btn btn-secondary" href="{% url 'shop:product-detail' product.id %}">Отменить</a>
            </div>
        </div>
        </form>

    </div>
{% endblock %}